export const projects = [
    { category:'Web',
     title: 'Odo',
     image:'/odo.png',
     preview:'',
     description: 'Meet your hopeless romantic',
     githubLink: 'https://github.com/0xNunana/Car_Dwom',
     liveDemoLink: 'https://odo-git-development-0xnunana.vercel.app/',
   },
     {
       category:'Web',
       title: 'CarDwom',
       image:'/hero.png',
       preview:'',
       description: 'Find,book or rent a car',
       githubLink: 'https://github.com/0xNunana/Car_Dwom',
       liveDemoLink: 'https://car-dwom.vercel.app/',
     },
     {
       category:'Mobile',
         title: 'Uber-clone',
         image:'/home.png',
         preview:'',
         description: 'Fast and Affordable rides',
         githubLink: 'https://github.com/0xNunana/Uber-clone',
         liveDemoLink: 'https://project1.example.com',
       },
       {
         category:'Mobile',
           title: 'Xing',
           image:'/xing.png',
           preview:'',
           description: 'Your deliverables expert',
           githubLink: 'https://github.com/0xNunana/Xing',
           liveDemoLink: 'https://project1.example.com',
         },
         {
            category:'Web',
            title: 'Jumia ',
            image:'/jumia.png',
            preview:'',
            description: 'Jumia Marketplace',
            githubLink: 'https://github.com/0xNunana/Jumia',
            liveDemoLink: 'https://jumia-sand.vercel.app/',
          },
        {
            category:'Mobile',
              title: 'Signal',
              image:'/login.png',
              preview:'',
              description: 'Signal Messenger Clone',
              githubLink: 'https://github.com/0xNunana/Signal-clone',
              liveDemoLink: 'https://project1.example.com',
            },
    // Add more projects as needed
  ];
